using System;
using System.Linq;
using System.Text;
using System.Threading;
using CodeGenerator.Generators;
using CodeGenerator.Mappers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CodeGenerator;

[Generator]
public sealed class TypeScriptGenerator : IIncrementalGenerator
{
    private static readonly ITypeMapper _typeMapper = new TypeScriptTypeMapper();

    private static readonly IFragmentGenerator[] _fragmentGenerators =
    [
        new EnumFragmentGenerator(),
        new InterfaceFragmentGenerator(_typeMapper),
    ];

    private static readonly ServiceFragmentGenerator _serviceGenerator = new(_typeMapper);

    // Emitted once whenever at least one [FrontendService] exists.
    private const string ApiFetchContent =
        "interface FetchOptions extends Omit<RequestInit, 'body'> {\n" +
        "  body?: unknown;\n" +
        "  params?: Record<string, string | number | boolean | null | undefined>;\n" +
        "}\n\n" +
        "export async function apiFetch<T = void>(url: string, options?: FetchOptions): Promise<T> {\n" +
        "  const { body, params, ...rest } = options ?? {};\n" +
        "  let fullUrl = url;\n" +
        "  if (params) {\n" +
        "    const qs = Object.entries(params)\n" +
        "      .filter(([, v]) => v != null)\n" +
        "      .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`)\n" +
        "      .join('&');\n" +
        "    if (qs) fullUrl = `${fullUrl}${fullUrl.includes('?') ? '&' : '?'}${qs}`;\n" +
        "  }\n" +
        "  const res = await fetch(fullUrl, {\n" +
        "    ...rest,\n" +
        "    headers: { 'Content-Type': 'application/json', ...rest.headers },\n" +
        "    body: body !== undefined ? JSON.stringify(body) : undefined,\n" +
        "  });\n" +
        "  if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);\n" +
        "  if (res.status === 204) return undefined as T;\n" +
        "  return res.json() as Promise<T>;\n" +
        "}\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ── 1. Compile-time attribute definitions ────────────────────────────
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("FrontendModelAttribute.g.cs", """
                // <auto-generated/>
                namespace SourceCodeGen
                {
                    /// <summary>Marks a class, interface, or enum for TypeScript interface generation.</summary>
                    [System.AttributeUsage(
                        System.AttributeTargets.Class |
                        System.AttributeTargets.Enum  |
                        System.AttributeTargets.Interface)]
                    public sealed class FrontendModelAttribute : System.Attribute { }
                }
                """);

            ctx.AddSource("FrontendServiceAttribute.g.cs", """
                // <auto-generated/>
                namespace SourceCodeGen
                {
                    /// <summary>
                    /// Marks an ASP.NET Core controller for TypeScript service generation.
                    /// Each public action method with an HTTP attribute becomes an async function
                    /// calling apiFetch in the generated &lt;ControllerName&gt;Service.tsx file.
                    /// </summary>
                    [System.AttributeUsage(System.AttributeTargets.Class)]
                    public sealed class FrontendServiceAttribute : System.Attribute { }
                }
                """);
        });

        // ── 2. Output-path detection ─────────────────────────────────────────
        var outputPath = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax { Name.Identifier.Text: "AddSourceCodeGen" }
                },
                transform: static (ctx, _) =>
                {
                    var inv = (InvocationExpressionSyntax)ctx.Node;
                    return inv.ArgumentList.Arguments.Count > 0 &&
                           inv.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lit
                        ? lit.Token.ValueText
                        : null;
                })
            .Where(static p => p is not null)
            .Collect()
            .Select(static (paths, _) => paths.Length > 0 ? paths[0]! : "src/generated");

        context.RegisterSourceOutput(outputPath, static (spc, path) =>
            spc.AddSource("SourceCodeGenOutputPath.g.cs", $$"""
                // <auto-generated/>
                internal static class SourceCodeGenOutputPath
                {
                    public const string Value = @"{{path}}";
                }
                """));

        // ── 3. Model fragments ([FrontendModel]) ─────────────────────────────
        var modelFragments = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SourceCodeGen.FrontendModelAttribute",
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax
                          or EnumDeclarationSyntax
                          or InterfaceDeclarationSyntax,
                transform: static (ctx, ct) => GenerateModelFragment(ctx.TargetSymbol, ct))
            .Where(static f => f is not null)
            .Collect();

        // ── 4. Service fragments ([FrontendService]) ──────────────────────────
        var serviceFragments = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SourceCodeGen.FrontendServiceAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GenerateServiceFragment(ctx.TargetSymbol, ct))
            .Where(static f => f is not null)
            .Collect();

        // ── 5. Emit GeneratedTypeScriptContent ────────────────────────────────
        context.RegisterSourceOutput(modelFragments.Combine(serviceFragments), static (spc, pair) =>
        {
            var (models, services) = pair;

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("internal static class GeneratedTypeScriptContent");
            source.AppendLine("{");

            var seen = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);

            foreach (var item in Enumerable.OfType<TsFragment>(models).Where(item => seen.Add(item.Name)))
            {
                EmitFragment(source, item);
            }

            if (services.Length > 0)
            {
                if (seen.Add("apiFetch"))
                {
                    EmitFragment(source, new TsFragment("apiFetch", ApiFetchContent));
                }

                foreach (var item in Enumerable.OfType<TsFragment>(services).Where(item => seen.Add(item.Name)))
                {
                    EmitFragment(source, item);
                }
            }

            source.AppendLine("}");
            spc.AddSource("__ts_models.g.cs", source.ToString());
        });
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static TsFragment? GenerateModelFragment(ISymbol symbol, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (symbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var generator = Array.Find(_fragmentGenerators, g => g.CanHandle(type));
        var content   = generator?.Generate(type, ct);
        return content is null ? null : new TsFragment(type.Name, content);
    }

    private static TsFragment? GenerateServiceFragment(ISymbol symbol, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (symbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var content = _serviceGenerator.Generate(type, ct);
        if (content is null)
        {
            return null;
        }

        var name = type.Name.EndsWith("Controller", StringComparison.Ordinal)
            ? type.Name.Substring(0, type.Name.Length - "Controller".Length) + "Service"
            : type.Name + "Service";
        return new TsFragment(name, content);
    }

    private static void EmitFragment(StringBuilder source, TsFragment fragment)
    {
        var content = "// AUTO-GENERATED — do not edit manually\n\n" + fragment.Content;
        source.Append("    public const string ").Append(fragment.Name).Append(" = @\"")
              .Append(content.Replace("\"", "\"\""))
              .AppendLine("\";");
    }

    private sealed record TsFragment(string Name, string Content);
}
