using System;
using System.Text;
using System.Threading;
using CodeGenerator.Generators;
using CodeGenerator.Mappers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CodeGenerator;

[Generator]
public sealed class TypeScriptGenerator : IIncrementalGenerator
{
    // Stateless services — safe as static readonly fields
    private static readonly ITypeMapper TypeMapper = new TypeScriptTypeMapper();

    private static readonly IFragmentGenerator[] FragmentGenerators =
    [
        new EnumFragmentGenerator(),
        new InterfaceFragmentGenerator(TypeMapper),
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("FrontendModelAttribute.g.cs", """
                // <auto-generated/>
                namespace SourceCodeGen
                {
                    /// <summary>
                    /// Marks a class, interface or enum for TypeScript code generation.
                    /// </summary>
                    [System.AttributeUsage(
                        System.AttributeTargets.Class |
                        System.AttributeTargets.Enum  |
                        System.AttributeTargets.Interface)]
                    public sealed class FrontendModelAttribute : System.Attribute { }
                }
                """));

        // Detect AddSourceCodeGen("path") calls in the compilation to embed the output path.
        var outputPath = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax { Name.Identifier.Text: "AddSourceCodeGen" }
                },
                transform: static (ctx, _) =>
                {
                    var inv = (InvocationExpressionSyntax)ctx.Node;
                    return inv.ArgumentList.Arguments.Count > 0 &&
                           inv.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lit
                        ? lit.Token.ValueText
                        : (string?)null;
                })
            .Where(static p => p is not null)
            .Collect()
            .Select(static (paths, _) => paths.Length > 0 ? paths[0]! : "src/generated");

        context.RegisterSourceOutput(outputPath, static (spc, path) =>
            spc.AddSource("SourceCodeGenOutputPath.g.cs", $$"""
                // <auto-generated/>
                internal static class SourceCodeGenOutputPath
                {
                    public const string Value = @"{{path}}";
                }
                """));

        var fragments = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SourceCodeGen.FrontendModelAttribute",
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax
                          or EnumDeclarationSyntax
                          or InterfaceDeclarationSyntax,
                transform: static (ctx, ct) => GenerateFragment(ctx.TargetSymbol, ct))
            .Where(static f => f is not null)
            .Collect();

        context.RegisterSourceOutput(fragments, static (spc, fragments) =>
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("internal static class GeneratedTypeScriptContent");
            source.AppendLine("{");

            var seen = new System.Collections.Generic.HashSet<string>();
            foreach (var item in fragments)
            {
                if (item is not { } model || !seen.Add(model.Name)) continue;

                var content = "// AUTO-GENERATED — do not edit manually\n\n" + model.Content;
                source.Append($"    public const string {model.Name} = @\"")
                      .Append(content.Replace("\"", "\"\""))
                      .AppendLine("\";");
            }

            source.AppendLine("}");
            spc.AddSource("__ts_models.g.cs", source.ToString());
        });
    }

    private static TsFragment? GenerateFragment(ISymbol symbol, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is not INamedTypeSymbol type) return null;

        var generator = Array.Find(FragmentGenerators, g => g.CanHandle(type));
        var content   = generator?.Generate(type, ct);

        return content is null ? null : new TsFragment(type.Name, content);
    }

    private sealed record TsFragment(string Name, string Content);
}