<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TsWriter</RootNamespace>

        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>

        <AssemblyName>TsxWriter</AssemblyName>

        <SelfContained>false</SelfContained>
        <PublishTrimmed>false</PublishTrimmed><!-- Trimming can break reflection -->
    </PropertyGroup>

</Project>
